
const ejercicios = [

    {
        id: 1,
        ejercicio: "Crunch",
        categoria: "Abdominales",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2000/07/crunch-au-sol-exercice-musculation.gif",
        descripcion: "Los abdominales son un movimiento básico que se enfoca en los músculos abdominales, especialmente el músculo recto del abdomen (el músculo del paquete de seis) y los oblicuos. Como no requiere de ningún equipo ni máquina, es uno de los primeros ejercicios que haces en casa cuando quieres trabajar los abdominales. Con la técnica adecuada, este ejercicio de abdominales desarrollará la fuerza central y lo preparará para ejercicios de peso corporal más complejos, como la tabla lateral , flexiones y V-ups. Incluso si no está buscando abdominales fuertes , un núcleo fuerte lo ayudará a levantar más pesas, sentadillas, peso muerto y press de banca más pesado.",
        consejo1: "No tire de su cuello. Esto limita el trabajo de los abdominales y es probable que traumatice su cuello.",
        consejo2: "Es tentador dejar que los hombros caigan hacia el suelo, pero el mejor enfoque es mantener los abdominales contraídos durante todo el movimiento. No dejes caer los hombros por completo en el suelo.",
        consejo3: "Tenga cuidado de no caer al suelo al regresar a la posición inicial. Los movimientos cuesta arriba y cuesta abajo deben ser controlados. ",
        consejo4: "Para realizar este ejercicio con comodidad, un suelo o colchoneta de fitness limitará la sensación de aplastamiento de las vértebras contra el suelo.",
        consejo5: "Si no siente que sus abdominales se contraen, puede hacer algunas repeticiones con ambas manos sobre el estómago. Esta técnica permite tener una mejor conexión entre el cerebro y los músculos y ayudar a reclutar un máximo de fibras musculares.",
        paso1: "Acuéstese sobre una colchoneta de ejercicios con las rodillas dobladas y los pies en el suelo.",
        paso2: "Coloque ambas manos en la parte posterior de su cabeza sin cruzar los dedos. Su columna y pelvis deben estar en una posición neutral.",
        paso3: "Exhala y contrae los abdominales mientras levantas la parte superior del cuerpo del piso.",
        paso4: "Una vez que sus abdominales estén completamente contraídos y la parte superior de su espalda no toque el piso, baje lentamente a la posición inicial.",
        paso5: "Repita el movimiento hasta que haya alcanzado el número deseado de repeticiones.",
        paso6: "",
        paso7: "",
        paso8: "",
        paso9: "",
        paso10: "",
    },
    {
        id: 2,
        ejercicio: "Abdominales rechazados",
        categoria: "Abdominales",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2022/02/sit-up-decline.gif",
        descripcion: "Los abdominales declinados, comúnmente conocidos como abdominales declinados , son una variación más difícil de los abdominales clásicos . Por lo tanto, es un ejercicio para reservar para aquellos que tienen un cinturón abdominal bastante sólido y uno de los mejores ejercicios para desarrollar un impresionante paquete de seis. El “crujido de declive” puede ser un ejercicio de la vieja escuela, pero no se equivoque, también es uno de los más efectivos. ¿Por qué es diferente del crujido estándar? Porque requiere un mayor rango de movimiento, lo que estira los abdominales y crea mayor tensión para el practicante. Estos son bloques de construcción esenciales para desarrollar músculo y fuerza.",
        consejo1: "Puede configurar el banco en cualquier ángulo de inclinación, siempre que pueda realizar sus abdominales con una buena técnica. Si encuentra que el ángulo que está utilizando es demasiado exigente, ajuste el banco a un ángulo ligeramente menos pronunciado.",
        consejo2: "Nunca use sus manos para tirar de la cabeza. Esto no solo es malo para su cuello, sino que no le permitirá optimizar el compromiso de sus músculos abdominales.",
        consejo3: "Evite acostarse en el banco durante cada repetición para asegurarse de mantener una tensión óptima en los músculos objetivo.",
        consejo4: "",
        consejo5: "",
        paso1: "Ajuste el banco al ángulo deseado según su nivel de fuerza.",
        paso2: "Siéntate en el banco y coloca los pies debajo de los rodillos de espuma.",
        paso3: "Acuéstese en el banco y coloque las manos detrás de la cabeza o crúcelas sobre el pecho.",
        paso4: "Contraiga sus abdominales y levante su pecho tan alto como lo permitan sus abdominales sin sentarse por completo. Exhala durante esta fase.",
        paso5: "Vuelva a bajar mientras inhala, pero sin que los hombros y la parte superior de la espalda toquen el banco.",
        paso6: "Repita el movimiento hasta que haya alcanzado el número deseado de repeticiones.",
        paso7: "",
        paso8: "",
        paso9: "",
        paso10: "",
    },
    {
        id: 3,
        ejercicio: "Elevación de rodilla colgando",
        categoria: "Abdominales",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2000/07/releve-de-genoux-suspendu-exercice-musculation.gif",
        descripcion: "Si alguna vez ha intentado desarrollar abdominales fuertes , probablemente esté familiarizado con los abdominales . Pero este ejercicio solo hace muy poco para desarrollar esos músculos. Los movimientos de tipo crunch se enfocan en los abdominales superiores, por lo que si su grasa corporal es lo suficientemente baja, puede obtener dos abdominales, pero perderá cuatro para obtener todo. Por eso es importante dedicar tanto tiempo de entrenamiento a los abdominales inferiores como a los abdominales superiores, y hay pocos movimientos más adecuados para este propósito que la elevación de cadera con la pierna colgando. Las elevaciones de rodillas colgando son uno de los movimientos fundamentales que se deben dominar si se quiere aumentar el rendimiento en ejercicios como “toes to bar”, “L-sits”, “leg raises” y “V-ups”, entre otros.",
        consejo1: "La elevación de rodilla por encima de la cabeza se puede realizar usando un tempo (cadencia) para aumentar el tiempo bajo tensión , promover una mejor conciencia y control del cuerpo y mejorar la activación de los músculos abdominales. Esto se hace levantando lentamente las rodillas a un ritmo establecido (2-5 segundos), agregando una pequeña pausa en la parte superior (2-5 segundos), luego bajando las rodillas sin perder tensión (2-5 segundos).",
        consejo2: "Agregar una mancuerna, una pelota u otro tipo de peso liviano entre los pies es una excelente manera de agregar resistencia a este movimiento. Las elevaciones de rodilla suspendidas con peso ayudan a desarrollar la fuerza y ​​el volumen abdominales.",
        consejo3: "Si desea aumentar la velocidad, suba rápido, haga una pausa en la parte superior y lleve lentamente las rodillas a la posición inicial mientras mantiene la contracción.",
        consejo4: "Concéntrese en sentir la contracción en todo el rango de movimiento. No intentes hacer trampa para lograr un alto número de repeticiones. Si siente que sus abdominales se calientan al final de su serie, probablemente haya realizado el ejercicio correctamente.",
        consejo5: "",
        paso1: "Sujete una barra fija en lo alto, con las manos ligeramente más separadas que el ancho de los hombros .",
        paso2: "Debes usar un agarre por encima de la cabeza, lo que significa que tus palmas deben mirar hacia afuera cuando agarres la barra.",
        paso3: "Junte los muslos y lleve el ombligo hacia el interior del cuerpo.",
        paso4: "Una vez que haya encontrado el equilibrio y la parte inferior de la espalda esté plana, lleve lentamente las rodillas hacia el pecho, asegurándose de llevar los talones al nivel de la cadera.",
        paso5: "Una vez que las rodillas estén casi al nivel del pecho, haz una pausa y contrae los abdominales al máximo.",
        paso6: "Con control total, baje lentamente las rodillas y las piernas.",
        paso7: "Tenga cuidado de no perder tensión en el centro y la espalda para que pueda controlar la posición del cuerpo y evitar balancearse hacia adelante y hacia atrás.",
        paso8: "Llegado a la posición inicial, no sueltes tus abdominales y directamente realiza la siguiente repetición y así sucesivamente hasta completar tu serie.",
        paso9: "Si pierde la coordinación y/o no logra mantener el control sobre el rango completo de movimiento, comenzará a tambalearse, lo que degradará su técnica y disminuirá el interés del ejercicio.",
        paso10: "¡No olvides respirar! Como con todos los ejercicios abdominales, exhala al contraer e inhala al extender.",
    },
    {
        id: 4,
        ejercicio: "Elevaciones de piernas en silla romana",
        categoria: "Abdominales",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2022/04/releve-jambes-chaise-romaine-abdominaux.gif",
        descripcion: "a elevación de piernas en silla romana (en inglés Captain's chair), realizada mediante una máquina de pesas llamada silla romana, es un ejercicio que fortalece los músculos abdominales . Al igual que con la elevación de la pierna colgando , la parte inicial del movimiento involucra a los flexores de la cadera (iliopsoas). Los músculos abdominales y oblicuos sirven solo como estabilizadores, ya que no hay flexión de la cintura. Sin embargo, los abdominales estarán muy estresados ​​desde el momento en que las piernas pasen por encima de la paralela.",
        consejo1: "Realice la elevación de la pierna estirada de manera controlada. No balancee las piernas hacia arriba y hacia abajo con impulso.",
        consejo2: "Mantenga los músculos abdominales contraídos y tensos durante todo el ejercicio.",
        consejo3: "Sus codos deben permanecer directamente debajo de sus hombros .",
        consejo4: "Para facilitar el ejercicio, hazlo con las rodillas dobladas.",
        consejo5: "",
        paso1: "Siéntese en la silla romana con los antebrazos apoyados en los soportes de espuma y la espalda apoyada en el respaldo.",
        paso2: "Manteniendo las piernas estiradas y la parte baja de la espalda presionada contra el respaldo, exhala mientras flexionas las caderas para levantar ambas piernas hasta que queden paralelas al piso.",
        paso3: "Mantén esta posición durante al menos un segundo.",
        paso4: "Inhala mientras bajas lentamente las piernas hasta la posición inicial.",
        paso5: "Repite este movimiento hasta completar el número previsto de repeticiones.",
        paso6: "",
        paso7: "",
        paso8: "",
        paso9: "",
        paso10: "",
    },
    {
        id: 5,
        ejercicio: "Ruleta abdominal",
        categoria: "Abdominales",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2022/02/roulette-abdominaux.gif",
        descripcion: "La rueda abdominal (en inglés “Ab Wheel” o “Ab Roller”) es un accesorio “inocente” a primera vista, pero que tiene un efecto formidable sobre tus músculos abdominales . Reforzar la faja abdominal tiene beneficios para cualquier tipo de deporte, pero también para el día a día.  Ya sea que quieras mejorar tu postura o tu fuerza, prevenir lesiones o sentirte mejor cada día, el trabajo de los abdominales, oblicuos y lumbares te permite fortalecer lo que los anglosajones llaman el “core” (en francés kernel) , en en otras palabras, los músculos de la correa abdominal sin los cuales el cuerpo no podría mantenerse erguido.",
        consejo1: "Dominar este accesorio requiere una parte superior del cuerpo fuerte y una buena fuerza central, por lo que este es un ejercicio para personas con un nivel de condición física intermedio o avanzado. Antes de entrenar con esta rueda, primero debe sentirse cómodo con los ejercicios básicos y las elevaciones de piernas.",
        consejo2: "Si está usando el rodillo para abdominales por primera vez, comience lentamente. Es fácil cometer el error de rodar demasiado, pero realmente debe concentrarse en rodar hacia adentro y hacia afuera suavemente, unas pocas pulgadas a la vez, para evitar estresar innecesariamente su columna.",
        consejo3: "Dada la fuerza requerida para ganar músculos abdominales, el rodillo para abdominales no será adecuado para todos. Las personas con lesiones abdominales o de la espalda baja deben evitar los rodillos abdominales hasta que se recuperen por completo.",
        consejo4: "",
        consejo5: "",
        paso1: "Arrodíllese sobre una colchoneta y coloque la rueda de abdominales frente a usted, directamente debajo de sus hombros .",
        paso2: "Antes de comenzar a hacer el movimiento, contraiga los músculos abdominales metiendo el ombligo y manteniendo la columna neutral y la espalda plana.",
        paso3: "Sujete cada manija lateral y mantenga los brazos rectos y estabilizados, antes de girar lentamente la rueda de manera controlada.",
        paso4: "Haz una pausa justo antes de sentir que tu espalda se arquea y vuelve lentamente a la posición inicial, manteniendo los abdominales tensos.",
        paso5: "Continúe trabajando en un mayor rango de movimiento extendiendo más las caderas a medida que gana fuerza.",
        paso6: "Haz tantas repeticiones como puedas y detente justo antes de que tu técnica se descomponga. Tómese un descanso y repita una serie hasta completar el número de series previstas.",
        paso7: "",
        paso8: "",
        paso9: "",
        paso10: "",
    },
    {
        id: 6,
        ejercicio: "Elevación de piernas colgando",
        categoria: "Abdominales",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2022/02/releve-de-jambes-suspendu.gif",
        descripcion: "La elevación de piernas colgando es un ejercicio ideal para trabajar los abdominales inferiores . Todo lo que necesitas para este ejercicio es un lugar para pasar el rato. Puede ser una barra de dominadas o un árbol.",
        consejo1: "La velocidad es muy importante en este ejercicio. Si balanceas las piernas, el impulso creado ayudará a levantarlas, a expensas de tus abdominales, que no se beneficiarán mucho del ejercicio.",
        consejo2: "Además, no dejes que tu cuerpo se balancee por la misma razón. Mantenga su torso lo más quieto y estable posible.",
        consejo3: "Los practicantes avanzados pueden agregar una carga (una mancuerna, por ejemplo) que sostendrán entre sus pies.",
        consejo4: "Disminuir la velocidad del descenso maximiza el trabajo muscular (y limita el impulso). Así que no dejes que tus piernas “caigan hacia atrás” una vez que las hayas llevado a la posición alta.",
        consejo5: "La exhalación durante el levantamiento de piernas permite una mejor contracción de los músculos de la faja abdominal. Así que inhala mientras bajas las piernas.",
        paso1: "Una vez que esté suspendido, estire la sección media. Mientras mantiene las piernas rectas, levántelas lentamente. Necesitas levantar las piernas lo más alto posible.",
        paso2: "Una vez que estés suspendido, contrae los músculos abdominales para levantar las piernas manteniéndolas rectas.",
        paso3: "Levante las piernas lo más alto posible.",
        paso4: "Baje lentamente las piernas hasta la posición inicial.",
        paso5: "Repite el movimiento tantas veces como puedas o hasta completar el número de repeticiones planeado.",
        paso6: "",
        paso7: "",
        paso8: "",
        paso9: "",
        paso10: "",
    },
    {
        id: 7,
        ejercicio: "Tabla lateral",
        categoria: "Abdominales",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2022/01/planche-laterale-obliques.gif",
        descripcion: "El ejercicio de plancha lateral es un excelente ejercicio que trabaja toda la faja abdominal, pero principalmente los músculos oblicuos. Los músculos de los hombros , las caderas, las piernas y los abdominales son estabilizadores secundarios en este ejercicio.  La tabla lateral es efectiva para desarrollar fuerza, estabilidad y flexibilidad en las caderas y la espalda baja . Puede hacer planchas laterales como ejercicio de calentamiento para activar los músculos abdominales, de la cadera y de la espalda baja antes de hacer un entrenamiento de espalda y piernas. También puedes hacer planchas laterales como ejercicio final en cualquier entrenamiento .",
        consejo1: "No dejes que la mitad de tu cuerpo se hunda. Manténgase siempre perfectamente recto.",
        consejo2: "Para asegurarte de que tu técnica sea la correcta, ¡haz la plancha lateral frente al espejo!",
        consejo3: "Trate de mantener una posición de tabla durante un minuto completo. Para más intensidad, simplemente mantén la posición por más tiempo.",
        consejo4: "También contrae los músculos de los glúteos para mantener una posición adecuada.",
        consejo5: "No dejes que tu pecho gire hacia el suelo.",
        paso1: "Acuéstese en el suelo de lado.",
        paso2: "Dobla el codo y colócalo debajo del hombro.",
        paso3: "Levante su cuerpo para que su cadera no toque el piso.",
        paso4: "Lleva la cadera lo más alto posible y mantén esta posición durante el tiempo que hayas determinado.",
        paso5: "Una vez que hayas completado el movimiento, cambia de lado para trabajar los músculos oblicuos del otro lado. Hacer el mismo trabajo por la misma cantidad de tiempo.",
        paso6: "",
        paso7: "",
        paso8: "",
        paso9: "",
        paso10: "",
    },
    {
        id: 8,
        ejercicio: "Flexiones oblicuas en banco a 45° lumbares",
        categoria: "Abdominales",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2000/07/flexions-des-obliques-banc-lombaire-45-exercice-musculation.gif",
        descripcion: "Las curvas laterales del busto (curva lateral 45) le permiten apuntar a sus oblicuos externos. Este ejercicio se realiza mejor en un banco lumbar de 45°, un dispositivo originalmente diseñado para extensiones lumbares y que se encuentra en la mayoría de los gimnasios.",
        consejo1: "Se recomiendan series largas (mínimo 20 repeticiones) para afinar la talla. Las series cortas con rellenos adicionales en particular tenderán a engrosar el tamaño.",
        consejo2: "Tenga cuidado de no inclinarse hacia adelante o hacia atrás (solo hacia un lado). En otras palabras, mueva su torso solo hacia los lados. Girar el tronco (o incluso las caderas) hacia la derecha o hacia la izquierda es el mayor error.",
        consejo3: "Baje el busto tanto como sea posible (esto le permite estirar los músculos objetivo tanto como sea posible). Si no siente un estiramiento, probablemente no tenga suficiente rango de movimiento.",
        consejo4: "Ascender lentamente y de manera controlada.",
        consejo5: "Concéntrate en flexionar los oblicuos y no dudes en realizar una contracción forzada al final del movimiento.",
        paso1: "Ajuste el asiento para que la parte superior de su cuerpo pueda moverse cómodamente desde sus caderas hasta el piso.",
        paso2: "Acuéstese de lado en el banco lumbar (banco de hiperextensión de 45 grados), las caderas en el soporte y el pecho expuesto.",
        paso3: "Apoye sus pies contra los calcetines de espuma debajo. Puedes cruzar las piernas si te sientes más cómodo.",
        paso4: "Coloque sus manos sobre su pecho o colóquelas al nivel de la cabeza.",
        paso5: "Lentamente, inclínese de lado hacia el piso lo más atrás y cómodamente posible. Cuando la parte superior de su cuerpo esté casi paralela, flexione los oblicuos con fuerza para volver a la posición inicial.",
        paso6: "Después de completar la serie, repite este movimiento con el otro lado.",
        paso7: "",
        paso8: "",
        paso9: "",
        paso10: "",
    },
    {
        id: 9,
        ejercicio: "Crunch con polea",
        categoria: "Abdominales",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2000/06/crunch-poulie-haute-exercice-musculation.gif",
        descripcion: "Si bien no hay nada intrínsecamente malo en hacer abdominales con pesas, sostener un disco contra el pecho o detrás de la cabeza puede ser incómodo y engorroso. Y cuanta más fuerza ganes, más difícil será agregar peso sin correr el riesgo de aplastarte la caja torácica o lastimarte el cuello. He aquí por qué es hora de cambiar a la contracción de rodillas con cable. El uso de una máquina equipada con una polea te permite añadir peso mediante un pasador, y la tensión constante del cable hace que tus músculos abdominales tengan que trabajar duro en cada momento del ejercicio, haciendo que este ejercicio sea más efectivo que el clásico crunch.",
        consejo1: "Las caderas deben mantenerse altas y bloqueadas durante la serie para evitar forzar los flexores de la cadera y permitir un rango completo de movimiento. Si las caderas están demasiado bajas, no podrás hacer una contracción completa. El movimiento de las caderas durante las repeticiones significa que estás usando el peso de tu cuerpo y los flexores de la cadera para realizar el movimiento.",
        consejo2: "La posición de las manos también condiciona el rango de movimiento y la longitud de la palanca utilizada para realizar el ejercicio. Sostenga la cuerda juntando las manos al nivel de la frente, no al nivel de los hombros .",
        consejo3: "Con una contracción abdominal, concéntrese en lograr una contracción poderosa y profunda (con la mayor flexión posible de la columna). La posición es crucial. Queremos que la columna esté al menos neutral en la parte superior y completamente flexionada en la parte inferior, manteniendo el control durante todo el movimiento. Concretamente, intente llevar los codos lo más posible hacia las rodillas (hacia la parte superior de los muslos).",
        consejo4: "Encuentra el ángulo recto de los muslos. Tus muslos deben formar un ángulo muy cercano a la perpendicular con el suelo, tal vez 5 o 10 grados hacia atrás, como máximo. Si avanza demasiado, el impulso del torso inclinado hacia adelante lo ayudará a hundirse en la contracción. Si retrocedes demasiado, tus isquiotibiales te ayudarán a hacer el movimiento.",
        consejo5: "",
        paso1: "Tome una posición al lado de una máquina equipada con una polea con una cuerda atada a ella.",
        paso2: "Siéntese con una carga adecuada y sujete las manijas de manera que las palmas de las manos queden hacia adentro.",
        paso3: "Ponte de rodillas y, frente al dispositivo, bloquea las asas de la cuerda contra tus oídos.",
        paso4: "Tu busto es firme e inclinado ligeramente hacia adelante. Esta es la posición inicial.",
        paso5: "Comience el movimiento contrayendo los abdominales y exhalando mientras se inclina.",
        paso6: "En el punto de máxima contracción, aprieta los abdominales con fuerza antes de volver lentamente a la posición inicial. Inhala durante esta fase del movimiento.",
        paso7: "No permita que la pila de pesas vuelva a caer a la posición inicial hasta que se complete el conjunto.",
        paso8: "",
        paso9: "",
        paso10: "",
    },
    {
        id: 10,
        ejercicio: "Montañista",
        categoria: "Abdominales",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2000/06/mountain-climber-exercice-musculation.gif",
        descripcion: "El alpinista es un excelente ejercicio para mejorar el encamisado , la resistencia cardiovascular y la agilidad. Este ejercicio, que se dirige principalmente a los músculos de la faja abdominal, te permite ejercitar varios grupos musculares diferentes, lo que lo convierte en un buen ejercicio para trabajar todo el cuerpo. De hecho, al realizar este movimiento, tus hombros , brazos y pectorales estabilizan la parte superior de tu cuerpo, mientras que tu busto estabiliza el resto de tu cuerpo. Este ejercicio para abdominales y oblicuos será por tanto interesante para realizar como parte de un programa de entrenamiento para adelgazar .",
        consejo1: "Cuando el movimiento esté bien dominado, es posible que contenga la respiración. No olvides respirar.",
        consejo2: "Debes realizar el movimiento con una buena técnica no solo para maximizar la efectividad del ejercicio, sino también para evitar lesiones. Un error común que cometen los principiantes, por ejemplo, es rebotar en los pies al realizar el movimiento. Los rebotes pueden hacerte pensar que el ejercicio es más duro, cuando en realidad la movilización de los músculos abdominales es menor.",
        consejo3: "Otro error técnico que puede cometer, especialmente cuando el movimiento se acelera, es no terminar completamente el movimiento cuando los dedos de los pies tocan el suelo mientras lleva las rodillas hacia el pecho. Si esto sucede, no obtendrá todos los beneficios del ejercicio y corre el riesgo de lesionarse.",
        consejo4: "Si no está familiarizado con este movimiento, no es raro perder el centro de gravedad y terminar con el cuerpo en una posición inclinada. Mantenga su cuerpo equilibrado y sus hombros por encima de sus manos.",
        consejo5: "Debes evitar hacer este ejercicio si sufres lesiones o inestabilidades en los hombros o la pelvis. El alpinista es un gran ejercicio para las rodillas, pero si te has operado o te vas a operar (por ejemplo, para reparar una lesión relacionada con el deporte o reemplazar una articulación afectada por la artritis), debes hablar con tu médico al respecto. o su fisioterapeuta antes de incorporar este movimiento en su programa.",
        paso1: "Ponte en posición de tabla , asegurándote de distribuir tu peso de manera uniforme entre las manos y los dedos de los pies.",
        paso2: "Verifique su posición: sus manos deben estar separadas al ancho de los hombros, la espalda plana , los abdominales contraídos y la cabeza alineada.",
        paso3: "Lleve su rodilla derecha hacia su pecho lo más lejos que pueda.",
        paso4: "Cambie de pierna, sacando la rodilla derecha y llevando la rodilla izquierda hacia adelante.",
        paso5: "Manteniendo las caderas bajas, empuja las rodillas hacia adelante y hacia atrás lo más lejos y rápido que puedas. Inhala y exhala alternativamente con cada cambio de pierna.",
        paso6: "",
        paso7: "",
        paso8: "",
        paso9: "",
        paso10: "",
    },
    {
        id: 11,
        ejercicio: "Crunch de pelota suiza",
        categoria: "Abdominales",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2000/07/crunch-swiss-ball-exercice-musculation.gif",
        descripcion: "Los abdominales son una excelente manera de fortalecer los abdominales . Realizados correctamente, ayudan a tonificar, aplanar y fortalecer los abdominales. Más allá del infame “paquete de seis”, los abdominales también ayudan a mejorar la estabilidad de la espalda baja , lo que mejora su postura. Realizar abdominales sobre una pelota suiza (crunch sobre bola de estabilidad) añade una dificultad adicional, ya que debes estabilizar tu cuerpo durante todo el movimiento.  La buena noticia: la pelota te obliga a poner más tensión en los músculos centrales, así como en los músculos de las piernas y los muslos, lo que te permite hacer un entrenamiento más efectivo. Además, ¡la pelota es más cómoda que el suelo!",
        consejo1: "Meta el ombligo hacia la columna y manténgalo allí durante todo el movimiento para mantener contraído el transverso del abdomen.",
        consejo2: "La ventaja de este ejercicio es que te permite trabajar con un amplio rango de movimiento. Para maximizar la contracción muscular, comience cada repetición estirando bien los abdominales.",
        consejo3: "Cerrar los ojos durante el movimiento te permitirá fortalecer tu propiocepción.",
        consejo4: "Para aumentar la dificultad al máximo, puedes apoyar solo una pierna en el suelo, obligando a los músculos de tu faja abdominal, y en particular a los oblicuos, a permanecer envainados al máximo.",
        consejo5: "",
        paso1: "Elige una pelota suiza (pelota de estabilidad) de una altura equivalente a la de tus rodillas y que sea muy firme.",
        paso2: "Siéntate sobre la pelota con las rodillas dobladas en un ángulo de 90 grados.",
        paso3: "Separe los pies mientras rueda hacia atrás, de modo que la parte inferior de la espalda descanse sobre la pelota.",
        paso4: "Para una contracción de la pelota, puede cruzar los brazos por encima del pecho o, para un ejercicio más difícil, puede estirar los brazos por encima de la cabeza.",
        paso5: "Comience el movimiento involucrando primero la parte superior del cuerpo y contrayendo los músculos abdominales. Se requiere un esfuerzo voluntario para que estos músculos se contraigan.",
        paso6: "Luego, usando el músculo recto del abdomen, levante los hombros y el pecho hacia el techo. Es aconsejable elegir un punto en el techo directamente encima de la cabeza para garantizar que el cuello permanezca en una posición neutra.",
        paso7: "Con control, baja los hombros y el pecho para tocar la pelota. Los abdominales deben permanecer tensos durante este ejercicio.",
        paso8: "",
        paso9: "",
        paso10: "",
    },
    {
        id: 12,
        ejercicio: "Rotaciones abdominales suspendidas",
        categoria: "Abdominales",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2021/11/rotations-abdos-obliques-suspendu.gif",
        descripcion: "Las rotaciones de los abdominales suspendidos son una variante de la elevación de piernas que te permite maximizar el trabajo de los oblicuos . Este es un excelente movimiento que le permite realizar un revestimiento dinámico de la correa abdominal.",
        consejo1: "Evite cualquier movimiento de impulso y controle el movimiento de sus caderas, rodillas y abdominales durante todo el ejercicio.",
        consejo2: "No realices este ejercicio si tienes problemas de espalda .",
        consejo3: "Normalmente no deberías sentir ninguna tensión significativa en la columna. Si la sensación de estiramiento del fieltro es desagradable o dolorosa, simplemente reduzca la amplitud de rotación.",
        consejo4: "",
        consejo5: "",
        paso1: "Tome una barra de dominadas y cuélguese con las manos un poco más separadas que el ancho de los hombros , con las piernas completamente extendidas. Asegúrate de que tu cuerpo esté recto y tus piernas permanezcan juntas. Esta es la posición inicial.",
        paso2: "Comience doblando las caderas y luego levantando las piernas verticalmente. Gire las piernas hacia el lado derecho dentro de los límites de su movilidad y fuerza. Contrae tus oblicuos y abdominales y luego gira hacia el lado opuesto.",
        paso3: "Realice el número deseado de repeticiones.",
        paso4: "Baje lentamente las caderas a la posición inicial y complete su serie.",
        paso5: "",
        paso6: "",
        paso7: "",
        paso8: "",
        paso9: "",
        paso10: "",
    },
    {
        id: 13,
        ejercicio: "Bandera del dragón",
        categoria: "Abdominales",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2022/07/dragon-flag.gif",
        descripcion: "La bandera del dragón es un ejercicio de culturismo que se hizo famoso por el maestro de artes marciales Bruce Lee. Este es uno de los movimientos de construcción de abdominales más avanzados que lo ayudarán a lograr abdominales increíblemente fuertes y definidos , en otras palabras, el paquete de 6 que muchas personas están buscando. El movimiento de la bandera del dragón de Bruce Lee es ahora un ejercicio que forma parte de la cultura pop del mundo del fitness. A lo largo de los años, ha sido adoptado por entusiastas de la calistenia y el culturismo a quienes les gusta practicar movimientos difíciles. Este movimiento avanzado trabaja todas las partes del cuerpo, de la cabeza a los pies. Es difícil encontrar un ejercicio que pueda trabajar tantos músculos al mismo tiempo. La bandera del dragón involucra específicamente todos los músculos estabilizadores centrales y, debido a que requiere un movimiento excéntrico controlado, desarrolla fuerza rápidamente en comparación con otros ejercicios de aislamiento de los músculos abdominales .",
        consejo1: "Apunte los dedos de los pies para ayudar a mantener la alineación adecuada del cuerpo.",
        consejo2: "No pongas el peso de tu cuerpo sobre tu cuello. Asegúrese de mantener el peso sobre la parte superior de la espalda y los hombros.",
        consejo3: "Asegúrese de mantener las piernas juntas y rectas durante todo el movimiento.",
        consejo4: "No arquees la espalda. Al arquear la espalda baja, alivias los abdominales y transfieres el esfuerzo a la espalda baja, con el riesgo de lesionarte.",
        consejo5: "Asegúrate de calentar bien antes de hacer la bandera del dragón.",
        paso1: "Para comenzar, acuéstese boca arriba y coloque los brazos detrás de usted para sostenerse de un poste, una rejilla para sentadillas en posición vertical o un banco de pesas resistente. Algunas personas usan pesas rusas o mancuernas, pero usar algo fijo y estable es mejor y más seguro.",
        paso2: "Levante las caderas y desplace el peso sobre los hombros .",
        paso3: "Levante los pies, las piernas y el torso en línea recta.",
        paso4: "Una vez que llegue a la cima, manteniendo los abdominales y los glúteos apretados, baje lentamente las piernas con un movimiento controlado sin dejar que ninguna parte de su cuerpo toque el banco, excepto la parte superior de la espalda y los hombros.",
        paso5: "Repita el movimiento tanto como sea posible.",
        paso6: "",
        paso7: "",
        paso8: "",
        paso9: "",
        paso10: "",
    },
    {
        id: 14,
        ejercicio: "Flexiones laterales con mancuerna",
        categoria: "Abdominales",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2022/07/flexions-laterales-haltere.gif",
        descripcion: "Las sentadillas laterales con mancuernas son un gran ejercicio para trabajar los músculos oblicuos. El fortalecimiento de los músculos de la cintura es fundamental para la práctica de actividades físicas que requieren gran estabilidad, buen equilibrio y gran movilidad.Este ejercicio es particularmente efectivo para adelgazar la cintura si se realiza con cargas ligeras y un número elevado de repeticiones. De hecho, hacer este ejercicio con cargas pesadas y pocas repeticiones promoverá el desarrollo muscular de los músculos oblicuos y, por lo tanto, engrosará la cintura.",
        consejo1: "Mantenga siempre la espalda recta, mire hacia adelante e inclínese solo al nivel del torso.",
        consejo2: "Concéntrate en estirar y contraer los músculos oblicuos.",
        consejo3: "Mantenga las mancuernas cerca del cuerpo.",
        consejo4: "Este ejercicio también se puede hacer sentado en el borde de un banco.",
        consejo5: "Si no tienes mancuernas, puedes hacer este ejercicio con una goma elástica.",
        paso1: "Tome una mancuerna con la mano derecha y sosténgala del lado derecho.",
        paso2: "Con los pies separados al ancho de los hombros , contrae los músculos abdominales y abre el pecho. Mantenga las rodillas ligeramente flexionadas.",
        paso3: "Coloque su mano izquierda en el costado de su cabeza o en su cadera. Dobla la cintura hacia tu lado izquierdo. Deténgase cuando sienta una contracción del oblicuo izquierdo y un estiramiento del oblicuo derecho.",
        paso4: "Vuelve a la posición inicial y repite el movimiento hasta completar el número de repeticiones deseado.",
        paso5: "Cambia de lado y repite el ejercicio.",
        paso6: "",
        paso7: "",
        paso8: "",
        paso9: "",
        paso10: "",
    },
    {
        id: 15,
        ejercicio: "Crunch de bicicleta",
        categoria: "Abdominales",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2022/05/exercice-abdos-bicyclette.gif",
        descripcion: "El Crunch de bicicleta (en inglés air bike) es una variante avanzada del crunch. Este ejercicio se dirige a los abdominales (rectus abdominis), a los músculos oblicuos, pero también a los músculos serratos. También se utiliza el músculo transverso del abdomen (músculo profundo de la faja abdominal). Al no requerir ningún equipo, el crunch de bicicleta a menudo está presente en los programas de fortalecimiento de abdominales en el hogar. De hecho, es un ejercicio muy efectivo siempre que los realices correctamente.",
        consejo1: "Exhala fuerte como si apagaras las velas de un pastel y mantén la contracción por un segundo para mejorar la conexión mente-músculo.",
        consejo2: "Tirar de la cabeza con las manos ejerce una tensión excesiva sobre el cuello y puede causar lesiones. Las manos, por tanto, en ningún momento deben participar en la realización del movimiento.",
        consejo3: "",
        consejo4: "",
        consejo5: "",
        paso1: "Acuéstese en el suelo con las rodillas dobladas a 90 grados.",
        paso2: "Coloque sus manos detrás de su cabeza.",
        paso3: "Exhala llevando una rodilla hacia tu cara mientras llevas el codo opuesto a esa rodilla.",
        paso4: "Una vez que sus abdominales estén completamente contraídos, baje lentamente a la posición inicial y repita el movimiento con el lado opuesto.",
        paso5: "Repita hasta que haya completado el número deseado de repeticiones o la duración de entrenamiento prevista para el ejercicio.",
        paso6: "",
        paso7: "",
        paso8: "",
        paso9: "",
        paso10: "",
    },
    /*gluteos*/
    {
        id: 16,
        ejercicio: "Sentadillas",
        categoria: "Gluteos",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2021/11/homme-faisant-un-squat-avec-barre.gif",
        descripcion: "La sentadilla es el rey de todos los ejercicios, ¡trabaja más de 256 músculos en un solo movimiento! Ya sea que sea culturista, levantador de pesas o atleta competitivo, la sentadilla es un ejercicio compuesto imprescindible que debe ser parte de cualquier programa de entrenamiento con pesas .  En el levantamiento de pesas , es uno de los tres grandes movimientos, que incluyen la sentadilla, el peso muerto y el press de banca . Para los atletas, tener una sentadilla explosiva es un buen indicador del rendimiento en la cancha. Y para los culturistas, la sentadilla es un ejercicio compuesto que se enfoca en casi todos los músculos de la parte inferior del cuerpo y del núcleo.",
        consejo1: "Redondea la parte inferior de la espalda : ¡Es esencial que mantengas la espalda recta cuando te pones en cuclillas! Puede asegurarse de que su espalda esté recta manteniendo la mirada hacia adelante, el pecho hacia afuera y los omóplatos hacia atrás (dorsales contraídos). Mantenga los músculos abdominales tensos durante todo el movimiento para mantener la espalda en su lugar.",
        consejo2: "Empujar con las plantas de los pies : esto ejerce una presión innecesaria sobre las articulaciones y los tendones. Empuje siempre con todo el pie a partir de los talones.",
        consejo3: "Inclinarse hacia delante : este fenómeno se produce cuando tus caderas se elevan más rápido que tus hombros. Para evitar esto, haz repeticiones lentas y controladas y saca el trasero mientras desciendes. También mantén siempre tu pecho abultado hacia arriba.",
        consejo4: "No estás haciendo sentadillas lo suficientemente bajo : para aprovechar todo el potencial de las sentadillas, debes hacer sentadillas al menos hasta que tus muslos estén más o menos paralelos al suelo.",
        consejo5: "Las rodillas se adelantan demasiado : cuando te pones en cuclillas, tus caderas deben caer hacia abajo, no hacia adelante. Con una carga ligera, perfecciona tu técnica colocándote de lado frente a un espejo. Si sus rodillas se mueven demasiado hacia adelante, la barra puede tener una trayectoria demasiado hacia adelante al bajar. Corre el riesgo de perder el equilibrio y no poder reclutar sus músculos de manera óptima para volver a subir.",
        paso1: "Prepara la barra colocándola justo por debajo de la altura de los hombros y cargándola con la carga que quieras usar.",
        paso2: "Párese debajo de la barra con los pies separados al ancho de los hombros.",
        paso3: "Coloque la barra de modo que descanse sobre los músculos de la parte superior de la espalda ( trapecios superiores ), no sobre la columna. La barra debe estar bien posicionada y no ser fuente de estorbo o incomodidad. Si no, intente agregar espuma amortiguadora.",
        paso4: "Ahora coloque sus manos detrás de su espalda y agarre la barra con un agarre amplio para mayor estabilidad.",
        paso5: "Luego doble las rodillas y estire la espalda para prepararse para retirar la barra del estante.",
        paso6: "Manteniendo la espalda recta y mirando hacia adelante, empuja hacia arriba con las piernas y retira la barra del soporte.",
        paso7: "Da dos pasos hacia atrás para estabilizarte.",
        paso8: "Inhala lo más profundamente posible y aguanta la respiración. Debe sentir que su correa abdominal está completamente tensa. Baje la barra lentamente hasta que la movilidad de su cadera y tobillo lo permita, idealmente por debajo del paralelo. Una vez en la posición inferior, empújese hacia arriba con los talones. Es solo una vez en la posición alta que puedes exhalar, inhalar y si deseas rehacer una repetición, rehacer una inspiración completa y comenzar de nuevo la secuencia de movimiento. ",
        paso9: "",
        paso10: "",
    },
    {
        id: 17,
        ejercicio: "Peso muerto rumano",
        categoria: "Gluteos",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2022/04/souleve-de-terre-roumain.gif",
        descripcion: "El peso muerto rumano (RDL) es un ejercicio popular y efectivo para la cadena posterior . Los culturistas lo utilizan para fortalecer los glúteos y los isquiotibiales , mientras que los levantadores de pesas lo utilizan para aumentar su rendimiento en el peso muerto . ¡RDL debería estar en tu lista de ejercicios para hacer regularmente!Según la leyenda, el RDL recibió su nombre después de que los entrenadores de levantamiento de pesas olímpicos estadounidenses vieron a los atletas rumanos hacer el movimiento. En ese momento, Rumania era una nación dominante en el deporte, ¡y los estadounidenses pensaron que habían descubierto la razón!  Sea cierto o no, este nombre ayuda a diferenciar el RDL del peso muerto con las piernas rectas , que es una variación diferente. El peso muerto rumano es un ejercicio compuesto . Esto significa que varias articulaciones y músculos tienen que trabajar juntos. Este ejercicio trabaja tantos grupos musculares que es prácticamente un ejercicio de cuerpo completo. Dicho esto, los principales músculos utilizados por el RDL son los isquiotibiales y el glúteo mayor; en segundo lugar, los músculos erectores de la columna , los abdominales , el trapecio y los romboides.",
        consejo1: "Mantenga su cuello alineado con el resto de su espalda mientras se inclina.",
        consejo2: "Deja de doblar las caderas cuando sientas un estiramiento en los isquiotibiales. La barra no necesita llegar al suelo. De hecho, puedes detener perfectamente el movimiento cuando la barra llega a la altura de la rodilla, dependiendo de tu flexibilidad.",
        consejo3: "No se balancee hacia atrás en la parte superior del movimiento.",
        consejo4: "Use un cinturón de pesas para fortalecer la parte inferior de la espalda si levanta cargas pesadas.",
        consejo5: "Mantén los brazos rectos durante todo el movimiento: no tires de la barra con los brazos.        ",
        paso1: "Sostenga la barra con un agarre a la altura de los hombros . Si está usando una carga pesada, puede ser útil usar correas para levantar pesas para evitar que su agarre se debilite.",
        paso2: "Párate con los pies separados a la altura de las caderas. Tire de los hombros hacia abajo y hacia atrás, contraiga los abdominales y doble ligeramente las rodillas.",
        paso3: "Sin doblar más las piernas, empuja el trasero hacia atrás e inclínate hacia adelante desde las caderas, teniendo cuidado de no encorvar la zona lumbar . Baja la barra por tus piernas.",
        paso4: "Descienda tan bajo como lo permita su flexibilidad. Sin embargo, la barra no debe tocar el suelo.",
        paso5: "Invierta el movimiento llevando las caderas hacia adelante y enderezándose.",
        paso6: "Repite este movimiento hasta que hayas completado el número deseado de repeticiones.",
        paso7: "",
        paso8: "",
        paso9: "",
        paso10: "",
    },
    {
        id: 18,
        ejercicio: "Montado en banco",
        categoria: "Gluteos",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2000/06/montees-sur-banc-exercice-musculation.gif",
        descripcion: "Los step ups con mancuernas son un gran ejercicio completo para la parte inferior del cuerpo . Este movimiento trabaja los glúteos , cuádriceps y pantorrillas .          Es adecuado para todos los deportistas, ya que se puede modificar para ofrecer un entrenamiento efectivo , ya sea que recién haya comenzado a entrenar o que haya estado entrenando durante años.  Este ejercicio tiene un bajo riesgo de lesiones y, con algunos ajustes, es un buen ejercicio cardiovascular , de fuerza y ​​de equilibrio.",
        consejo1: "Mantenga la mirada hacia arriba y la espalda recta durante todo el ejercicio. Nunca dejes que tu espalda se redondee.",
        consejo2: "Para aumentar la intensidad y la dificultad, utilice una plataforma más alta. Cuanto más alta sea la plataforma, más intenso será el ejercicio.",
        consejo3: "Comience usando poco o nada de peso. Este ejercicio requiere mucho equilibrio y se requiere precaución.",
        consejo4: "",
        consejo5: "",
        paso1: "Prepara un banco de pesas y un par de mancuernas que sujetarás a un lado. También puede utilizar otro tipo de plataforma elevada.",
        paso2: "Levanta la rodilla izquierda y sube a la plataforma con el pie izquierdo.",
        paso3: "Una vez que su pie esté firmemente plantado en la superficie, use su talón izquierdo para apoyarse y levantarse. Coloque su pie derecho en la superficie también.",
        paso4: "Haga una breve pausa, luego retroceda con la pierna derecha para volver con cuidado a la posición inicial.",
        paso5: "Repita este movimiento hasta que haya hecho el número deseado de repeticiones, luego repítalo usando su pierna derecha.",
        paso6: "",
        paso7: "",
        paso8: "",
        paso9: "",
        paso10: "",
    },
    {
        id: 19,
        ejercicio: "Extensión de cadera en polea baja",
        categoria: "Gluteos",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2022/05/extension-hanche-poulie-basse.gif",
        descripcion: "Aunque las sentadillas y las estocadas son los ejercicios favoritos para desarrollar glúteos firmes, no son los únicos ejercicios disponibles para lograrlo. Por supuesto, son los que desarrollan la masa muscular y la fuerza, pero ciertos movimientos de aislamiento también son muy efectivos para trabajar estos músculos. Este es el caso de las extensiones de cadera en polea, que son un gran movimiento de aislamiento para trabajar los glúteos y los isquiotibiales .",
        consejo1: "Agárrate a la máquina para mantener tu cuerpo estable.",
        consejo2: "No patees la pierna de un lado a otro. Mantén el control del movimiento.",
        consejo3: "Puede encontrar que al rotar ligeramente externamente la pierna trabajada, logrará una mejor activación de los glúteos.",
        consejo4: "Este ejercicio es ideal para calentar y conectar el cerebro y los músculos de los glúteos antes de ejercicios compuestos como la sentadilla o el peso muerto .",
        consejo5: "",
        paso1: "Comience colocando una correa de tobillo en una polea baja.",
        paso2: "Manteniendo el torso recto y la pierna de trabajo estirada, exhala mientras extiendes las caderas y tiras del cable hacia atrás.",
        paso3: "Mantén la posición por un segundo y contrae los músculos de los glúteos.",
        paso4: "Inhala mientras regresas la pierna a la posición inicial.",
        paso5: "Repita el movimiento hasta que haya completado el número previsto de repeticiones.",
        paso6: "Repite el ejercicio con la otra pierna.",
        paso7: "",
        paso8: "",
        paso9: "",
        paso10: "",
    },
    {
        id: 20,
        ejercicio: "Patada de burro",
        categoria: "Gluteos",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2022/04/donkey-kick.gif",
        descripcion: "Para lograr un cuerpo más saludable, muchas personas recurren a ejercicios intensivos y programas de entrenamiento. Si bien los métodos de entrenamiento sofisticados tienen su lugar, si eres un principiante pueden no ser adecuados. Tome el entrenamiento de glúteos , por ejemplo. Hay docenas, si no cientos, de ejercicios de glúteos para tonificar y fortalecer los glúteos. Sin embargo, también hay muchos ejercicios más simples que pueden ser igual de efectivos, especialmente si eres nuevo en el entrenamiento de fuerza . La patada de burro trabaja los glúteos sin una máquina elegante, por lo que es un ejercicio ideal para las personas que hacen ejercicio en casa. También es fácil de aprender, por lo que es perfecto para principiantes.",
        consejo1: "Tenga cuidado de no hiperextender la zona lumbar durante todo el movimiento.",
        consejo2: "Levante la pierna hasta que la parte inferior de la espalda se arquee (baje) o las caderas giren o se inclinen; si sucede cualquiera de estas cosas, usted ha levantado la pierna demasiado alto.",
        consejo3: "Evite apresurarse para realizar el ejercicio con un rango de movimiento completo y una buena técnica.",
        consejo4: "Puede hacer que este ejercicio sea más difícil usando pesas en los tobillos.",
        consejo5: "Realiza 20 repeticiones en cada pierna durante 4-5 series.",
        paso1: "Póngase a cuatro patas, de modo que sus hombros estén directamente sobre sus manos y sus caderas sobre sus rodillas. Sus brazos deben estar rectos y sus manos deben estar separadas al ancho de los hombros con los dedos apuntando hacia adelante.",
        paso2: "Involucra tus músculos centrales para estabilizar tu pelvis y fortalecer tu espalda baja .",
        paso3: "Extiende desde la cadera y, manteniendo la rodilla doblada, levanta una pierna detrás de ti, llevando el talón hacia el techo.",
        paso4: "Baja la pierna y repite el mismo movimiento del mismo lado o cambiando de pierna si lo deseas.",
        paso5: "",
        paso6: "",
        paso7: "",
        paso8: "",
        paso9: "",
        paso10: "",
    },
    {
        id: 21,
        ejercicio: "Peso muerto",
        categoria: "Gluteos",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2021/12/souleve-de-terre.gif",
        descripcion: "El peso muerto es un ejercicio extremadamente popular y una verdadera prueba de la fuerza general del cuerpo. Es popular entre muchos levantadores de pesas, pero también entre culturistas, levantadores de pesas y atletas de CrossFit . El peso muerto consiste en levantar una carga desde el suelo hasta el nivel de la cadera sin usar el impulso para levantarla. Es conocido como uno de los tres grandes ejercicios para levantadores de pesas, a saber, la sentadilla , el press de banca y el peso muerto. Los culturistas usan el peso muerto para estimular el crecimiento muscular en toda su cadena posterior (músculos en la parte posterior del cuerpo). De hecho, el peso muerto trabaja principalmente los músculos isquiotibiales. Sin embargo, este es un ejercicio compuesto completo que también involucra los músculos de la espalda , los glúteos , los cuádriceps , los brazos y los abdominales .",
        consejo1: "Debe mantener el pliegue de la axila sobre la barra y la parte media del pie para permitir que la barra se mueva en línea recta.",
        consejo2: "El peso muerto es un movimiento de extensión de cadera, no un movimiento real de extensión de piernas como la sentadilla. Si coloca las caderas demasiado bajas, se pondrá en desventaja biomecánica y limitará su potencial para levantar cargas máximas.",
        consejo3: "Por el contrario, no debes iniciar el movimiento con la pelvis demasiado alta y las piernas estiradas. Por lo tanto, las caderas deben estar más bajas que los hombros.",
        consejo4: "",
        consejo5: "",
        paso1: "Encuentre suficiente espacio y comience colocando una barra en el piso.",
        paso2: "Acérquese a la barra y párese lo suficientemente cerca como para que la barra esté justo por encima de sus pies, con sus pies en el centro de la barra.",
        paso3: "Mantenga los pies separados al ancho de los hombros.",
        paso4: "Inclínese hacia adelante y agarre la barra con un agarre en pronación (hands over).",
        paso5: "Mantenga el pecho erguido, la columna vertebral neutra y los hombros hacia atrás. Lo más importante es mantener las caderas por encima de las rodillas. Esta es tu posición de inicio.",
        paso6: "Respira hondo, aguanta la respiración y levanta la barra del suelo, manteniendo la espalda baja recta. Asegúrate de que la barra siga una línea recta mientras estiras las rodillas y las caderas. Exhale en la parte superior del movimiento.",
        paso7: "Una vez que haya bloqueado las caderas, invierta el movimiento tirando de las caderas hacia atrás e inclinándose hacia adelante. Flexiona también las piernas durante esta fase de descenso para no colocar la barra con las piernas estiradas.",
        paso8: "Una vez que la barra esté en el suelo, vuelva a ponerse en posición y repita el movimiento hasta el número deseado de repeticiones.",
        paso9: "",
        paso10: "",
    },
    {
        id: 22,
        ejercicio: "Columpio con pesas rusas",
        categoria: "Gluteos",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2021/12/kettlebell-swing.gif",
        descripcion: "El swing con pesas rusas es un ejercicio de cuerpo completo que trabaja principalmente los músculos de la cadena posterior, con énfasis en los glúteos y los isquiotibiales . Este es un gran ejercicio preparatorio para aquellos que quieren incorporar un movimiento de flexión de cadera en su entrenamiento. Por lo tanto, es un muy buen ejercicio de calentamiento como preparación para un movimiento de peso muerto o sentadilla . Dicho esto, el swing con pesas rusas también es un excelente ejercicio para incorporar a tu programa para trabajar todos los músculos del cuerpo (full body) o como parte de una sesión tipo HIIT para quemar el máximo de calorías .",
        consejo1: "El swing debe ser un movimiento muy explosivo, con el objetivo de generar la extensión de la cadera lo más rápido posible.",
        consejo2: "Obviamente, la carga se desplazará hacia los talones en la parte cuesta abajo del ejercicio, pero no debes dejar que los dedos de los pies se levanten.",
        consejo3: "Tu barbilla debe acompañar tu busto, no te preocupes por mirar hacia arriba en la parte baja del movimiento.",
        consejo4: "Exhale con fuerza al extender las caderas e inhale mientras baja la carga.",
        consejo5: "Mantén la espalda plana. Cuando doble las rodillas y apunte el trasero hacia atrás, no redondee la espalda.",
        paso1: "Póngase en una posición con la espalda doblada hacia adelante, las rodillas ligeramente dobladas, los brazos apuntando hacia abajo, ambas manos en el mango de la pesa rusa, la barbilla hacia adentro y el peso centrado en los pies.",
        paso2: "Las piernas deben estar más separadas que el ancho de los hombros para que no te arriesgues a atrapar la pesa rusa en la espinilla.",
        paso3: "Comienza el movimiento llevando la pesa rusa ligeramente por delante del cuerpo solo con la fuerza de los hombros. Libere la tensión y deje que la pesa rusa vuelva a la posición inicial. Con la fuerza de la gravedad, la tetera debe retroceder un poco más hacia los glúteos.",
        paso4: "Aproveche este impulso para llevar la pesa rusa al nivel de los hombros. Para hacer esto, contrae firmemente los músculos de la parte inferior del cuerpo, y más particularmente los músculos de los glúteos. La carga debe entonces elevarse por sí sola, los brazos y los hombros solo están ahí para acompañar el movimiento de la tetera.",
        paso5: "Deje que la pesa rusa regrese a la posición inicial sin intentar dominar la carga.",
        paso6: "Repita el movimiento hasta el número deseado de repeticiones.",
        paso7: "",
        paso8: "",
        paso9: "",
        paso10: "",
    },
    {
        id: 23,
        ejercicio: "Sentadilla con barra frontal",
        categoria: "Gluteos",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2021/11/squat-barre-devant-front.gif",
        descripcion: "La sentadilla frontal ( front squat clean grip ) es una variación de la sentadilla y un ejercicio utilizado para trabajar los músculos de las piernas, y en particular los músculos cuádriceps . El movimiento de sentadilla es un movimiento básico y debe ser practicado por todas las personas sin discapacidad a lo largo de su vida. Es importante encontrar una variación que sea cómoda de realizar y practicarla con regularidad.",
        consejo1: "Si está haciendo una sentadilla frontal por primera vez, elija una barra ligera; esto le permitirá adaptarse a la técnica antes de levantar una carga más grande.",
        consejo2: "El ángulo de los dedos de los pies es muy individual, por lo que vale la pena experimentar con varias posiciones para encontrar la que más le convenga.",
        consejo3: "Es posible usar 2 o 3 dedos al hacer la sentadilla frontal, ya que esto quita tensión a la muñeca.",
        consejo4: "Si no puede sostenerse en la posición de rejilla delantera, intente con la posición de sujeción con los brazos cruzados.",
        consejo5: "Es aceptable cierto movimiento de las rodillas hacia adelante en relación con los dedos de los pies, siempre que las rodillas no se desvíen excesivamente hacia adentro o hacia afuera. Las personas con fémures más largos necesitarán permitir que sus rodillas avancen más si quieren permanecer erguidas.",
        paso1: "Coloque la barra en un estante ligeramente por debajo del nivel de los hombros , de modo que las rodillas queden ligeramente dobladas.",
        paso2: "Coloque las manos justo fuera del ancho de los hombros, alcance debajo de la barra y déjela descansar sobre los hombros mientras empuja los codos frente al cuerpo. Tus tríceps deben permanecer paralelos al suelo. Mantenga un cuello neutral y una espalda plana . Esta es tu posición de inicio.",
        paso3: "Inhala y suelta la barra llevando las caderas hacia adelante y estirando las piernas.",
        paso4: "Haz una sentadilla (doblar las piernas) doblando las rodillas y empujando las caderas hacia atrás al mismo tiempo.",
        paso5: "Una vez que los muslos estén paralelos al suelo, comience a invertir el movimiento. Mantén tus abdominales contraídos y empuja tus pies hacia el piso.",
        paso6: "Complete el movimiento exhalando y extendiendo completamente las caderas y las rodillas.",
        paso7: "",
        paso8: "",
        paso9: "",
        paso10: "",
    },
    {
        id: 24,
        ejercicio: "Sentadilla de copa con pesas rusas",
        categoria: "Gluteos",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2021/12/squat-goblet-kettlebell.gif",
        descripcion: "La sentadilla de copa con pesas rusas (también llamada girya) es una variación de la sentadilla de copa . Este es un ejercicio que fortalece los músculos de las piernas. Este ejercicio te permite fortalecer los cuádriceps , para desarrollar una mejor movilidad, flexibilidad y estabilidad de las caderas. La sentadilla en copa con pesas rusas es un excelente movimiento de rehabilitación, pero sobre todo un ejercicio de fortalecimiento muscular. Le permite realizar flexiones de piernas más profundas que con todas las demás variaciones de sentadillas.",
        consejo1: "Si tienes problemas con las sentadillas con barra, esta es la mejor versión para ayudarte a practicar la sentadilla vertical.",
        consejo2: "Una sentadilla de copa con pesas rusas más profunda dará como resultado un mejor desarrollo de las piernas, ya que los aductores estarán involucrados en el movimiento.",
        consejo3: "Mantenga siempre los codos en alto para mantener un mejor equilibrio.",
        consejo4: "Es aceptable cierta traslación hacia adelante de las rodillas en relación con los dedos de los pies, siempre que las rodillas no se desvíen excesivamente hacia adentro o hacia afuera. Las personas con fémures más largos necesitarán dejar que sus rodillas avancen más si quieren permanecer erguidas.",
        consejo5: "",
        paso1: "Coloque una pesa rusa a la altura de la parte superior del pecho. Sujete las asas de la tetera con ambas manos.",
        paso2: "Sus pies estarán separados al ancho de los hombros (o ligeramente más anchos) y apuntando ligeramente hacia afuera.",
        paso3: "Respira hondo y baja empujando las caderas hacia atrás y doblando las rodillas al mismo tiempo.",
        paso4: "Continúe descendiendo hasta que el pliegue de la cadera esté más bajo que las rodillas.",
        paso5: "Vuelve a subir empujando los pies hacia el suelo, estirando las rodillas y las caderas hasta que estés de nuevo en una posición alta. Exhalar.",
        paso6: "Repite este movimiento hasta que hayas completado el número deseado de repeticiones.",
        paso7: "",
        paso8: "",
        paso9: "",
        paso10: "",
    },
    {
        id: 25,
        ejercicio: "Empuje de cadera unilateral",
        categoria: "Gluteos",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2021/10/hip-thrust-barre-unilateral.gif",
        descripcion: "El empuje de cadera unilateral es una variación del empuje de cadera . Este es un ejercicio que se utiliza para trabajar los músculos de los glúteos . Los glúteos son un grupo de tres músculos que forman las nalgas. Los músculos glúteos fuertes contribuyen a un físico bien equilibrado y realizan muchas funciones importantes, como mantener el torso erguido, levantarse de una posición sentada y subir escaleras, por nombrar algunas. Al trabajar cada lado por separado, puedes aislar completamente tus glúteos de forma unilateral, proporcionando un estímulo de entrenamiento de calidad.",
        consejo1: "Puede mantener la otra pierna recta o doblada.",
        consejo2: "Envuelve la barra con espuma protectora para evitar que lastime tus caderas.",
        consejo3: "Mantén tu busto rígido. Tu espalda no debe arquearse y tu pelvis no debe inclinarse.",
        consejo4: "Idealmente, debería buscar una línea recta entre las rodillas y los hombros en la parte superior del movimiento.",
        consejo5: "No use una barra que sea demasiado pesada para el empuje unilateral de la cadera, ya que esto puede ejercer demasiada torsión (fuerza de rotación) en las vértebras lumbares. Si quieres ir pesado, haz el clásico movimiento de empuje de cadera. Así que favorezca una carga ligera con series largas.",
        paso1: "Coloque una barra cargada paralela a un banco.",
        paso2: "Siéntate en el piso con las caderas debajo de la barra y la espalda apoyada contra el costado del banco.",
        paso3: "Sujeta la barra por cada lado.",
        paso4: "Manteniendo el busto rígido, exhala contrayendo los glúteos de la pierna activa y levanta las caderas hasta que la rodilla de la pierna de apoyo forme un ángulo de 90°.",
        paso5: "Mantén la posición durante dos segundos y contrae los glúteos.",
        paso6: "Inhala mientras bajas la barra flexionando la cadera. No dejes que la barra toque el suelo.",
        paso7: "Haz tus repeticiones y cambia de pierna.",
        paso8: "",
        paso9: "",
        paso10: "",
    },
    {
        id: 26,
        ejercicio: "Estocadas hacia adelante con pesas rusas",
        categoria: "Gluteos",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2021/12/fentes-avant-kettlebell.gif",
        descripcion: "La estocada con pesas rusas es un ejercicio que se enfoca en los cuádriceps , los glúteos , los isquiotibiales y los músculos de la pantorrilla .Debido al movimiento unilateral que requiere este ejercicio, se solicitarán los músculos abdominales . Sostener las pesas rusas mientras se lanza durante un período prolongado de tiempo también ayuda a fortalecer los antebrazos y los trapecios .",
        consejo1: "Cuando te balancees hacia adelante, no gires la rodilla hacia adentro en una posición de estocada.",
        consejo2: "Mantenga la cabeza erguida y la espalda recta durante todo el ejercicio. Nunca dejes que tu espalda se redondee.",
        consejo3: "Mantenga su cuerpo erguido, pero no extienda demasiado su columna lumbar.",
        consejo4: "Tenga en cuenta que con cualquier tipo de estocada, si desea enfatizar los cuádriceps, debe dar un paso un poco más pequeño y levantar los dedos.",
        consejo5: "Si desea enfatizar los glúteos y los isquiotibiales durante una estocada, dé un paso un poco más grande y levante el talón del pie.",
        paso1: "Tome un par de pesas rusas doblando las caderas y luego las rodillas. Mantenga la espalda recta y no encorvada hacia adelante.",
        paso2: "De pie, con los pies separados a la altura de los hombros , inhala y contrae los músculos abdominales, saca el pecho y lánzate hacia delante con la pierna izquierda. La estocada debe ser lo suficientemente larga como para que la pierna delantera forme un ángulo de 90 grados mientras la pierna trasera o derecha toca el suelo.",
        paso3: "Exhala, luego empuja con la pierna izquierda para volver a la posición inicial.",
        paso4: "Puede realizar estocadas con pesas rusas alternativamente o cambiar de pierna al final del número de repeticiones por serie.",
        paso5: "Repita hasta que haya alcanzado el número deseado de repeticiones.",
        paso6: "",
        paso7: "",
        paso8: "",
        paso9: "",
        paso10: "",
    },
    {
        id: 27,
        ejercicio: "Propulsor con pesas rusas",
        categoria: "Gluteos",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2021/12/thruster-kettlebell.gif",
        descripcion: "El propulsor con pesas rusas es una variación del propulsor con mancuernas . Es un ejercicio combinado que combina el movimiento de la sentadilla frontal con el de la prensa militar . Por lo tanto, el propulsor de pesas rusas trabaja los músculos de las piernas y los hombros . Los propulsores fueron popularizados por CrossFit . Este movimiento tiene muchas aplicaciones en el desarrollo de la fuerza, la masa muscular y la explosividad.",
        consejo1: "Contrae tus glúteos y abdominales mientras haces el movimiento.",
        consejo2: "Asegúrese de mantener el peso sobre los talones. Si se pone en cuclillas sobre los dedos de los pies, su cuerpo se balanceará hacia adelante y hacia atrás, lo que lo hará perder el equilibrio y lo pondrá en riesgo de caerse.",
        consejo3: "Concéntrese en mantener la espalda lo más recta posible durante todo el movimiento.",
        consejo4: "Puedes hacer propulsores con ambos brazos o alternar un brazo entre cada sentadilla.",
        consejo5: "",
        paso1: "Párese con las piernas separadas al ancho de los hombros y coloque dos pesas rusas sobre los hombros con un agarre neutral o ligeramente por encima de la cabeza.",
        paso2: "Inhala y realiza una sentadilla con las pesas rusas flexionando simultáneamente las rodillas y las caderas.",
        paso3: "Volviendo a la posición inicial, usa el impulso de la sentadilla para impulsar las pesas rusas en una prensa militar.",
        paso4: "Exhala una vez que las pesas rusas estén en la posición hacia arriba e invierte lentamente el movimiento mientras controlas las pesas rusas para llevarlas hacia tus hombros.",
        paso5: "Repita el movimiento hasta el número deseado de repeticiones.",
        paso6: "",
        paso7: "",
        paso8: "",
        paso9: "",
        paso10: "",
    },
    {
        id: 28,
        ejercicio: "Estocadas frontales con barra",
        categoria: "Gluteos",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2022/12/fente-avant-barre-femme.gif",
        descripcion: "Si está buscando un ejercicio que lo haga todo: desarrollar cuádriceps, glúteos e isquiotibiales, aumentar la fuerza funcional, mejorar el rendimiento atlético, mejorar el equilibrio e incluso quemar muchas calorías mientras tiene beneficios cardiovasculares, entonces debe incluir las estocadas en tus entrenamientos de la parte inferior del cuerpo.  La estocada en la barra (en inglés barbell lunges) solicita fuertemente los cuádriceps (frente de los muslos) y los glúteos. Los isquiotibiales también están involucrados en menor medida. Asimismo, los abdominales también se movilizan para estabilizar tu cuerpo.Una barra es el único equipo que necesitas. Sin embargo, cuanto más progreses, menos práctico será levantar la barra y colocarla en la parte superior de la espalda. Esta es la razón por la cual las estocadas con barra generalmente se realizan en un estante (en cuclillas).Las estocadas son un ejercicio excepcional para desarrollar músculos estéticos, y por eso son tan populares entre los atletas que practican musculación, CrossFit o entrenamiento de fuerza. Las estocadas son un movimiento calificado de funcional, es decir que permiten desarrollar la fuerza necesaria para realizar un movimiento de la vida cotidiana. Las estocadas son un movimiento fácil de realizar, ya sea con peso corporal o con pesas libres, y hay suficientes variaciones para mantenerte ocupado toda la vida sin aburrirte. Las estocadas se pueden incorporar en programas de entrenamiento de tipo circuito porque es un movimiento metabólicamente exigente (se siente como hacer cardio cuando haces muchas repeticiones).",
        consejo1: "Este ejercicio puede producir muchos dolores corporales retardados (DOMS). Por lo tanto, es recomendable comenzar gradualmente durante las primeras sesiones de entrenamiento, de lo contrario, corre el riesgo de caminar de forma extraña durante unos días.",
        consejo2: "A medida que desciende a la posición baja, mantenga la cabeza erguida, el pecho erguido, el pecho recto y la espalda plana (no redondee la espalda).",
        consejo3: "Hay innumerables posibilidades para hacer estocadas con barra. Los principiantes pueden comenzar con una barra o incluso con el peso corporal. Los levantadores de pesas olímpicos y los entusiastas de CrossFit a menudo realizan este ejercicio colocando la barra en la parte delantera de los hombros. Estos atletas también suelen hacer estocadas mientras sostienen la barra por encima de la cabeza (por encima de la cabeza).",
        consejo4: "Las estocadas a pie son una de las variantes más populares. En lugar de dar un paso adelante y luego volver a la misma posición inicial, las estocadas caminadas son exactamente lo que su nombre describe: caminas por la habitación. Esto requiere un espacio grande y, por lo tanto, no es necesariamente práctico en gimnasios pequeños o en casa (si el clima lo permite, las estocadas caminadas se pueden practicar al aire libre). La estocada inversa es otra variación muy popular en la que das un paso atrás en lugar de un paso adelante. Las estocadas diagonales y las estocadas laterales involucran otros músculos de las piernas en el movimiento.",
        consejo5: "Las estocadas también se pueden realizar con cualquier otro equipo de entrenamiento con pesas, como mancuernas, pesas rusas, chalecos de pesas, etc.",
        paso1: "Cargue la barra en un soporte para sentadillas.",
        paso2: "Pasa por debajo de la barra y colócala en la parte trasera de tus hombros como si fueras a hacer una sentadilla.",
        paso3: "Suelte suavemente la barra del estante hasta que tenga suficiente espacio frente a usted para dar un gran paso hacia adelante.",
        paso4: "Da un gran paso hacia adelante, apoya suavemente el pie delantero en el suelo y, al mismo tiempo, baja la rodilla trasera.",
        paso5: "Tus rodillas deben formar un ángulo de 90 grados en la parte inferior del movimiento.",
        paso6: "Con la fuerza de tu muslo delantero, vuelve a subir a la posición superior con un movimiento suave, asegurándote de mantener el equilibrio mientras vuelves a subir.",
        paso7: "Realice otra estocada con la misma pierna y repita este movimiento hasta que haya alcanzado el número deseado de repeticiones, luego cambie de pierna. Otra opción es alternar las piernas con cada repetición.",
        paso8: "",
        paso9: "",
        paso10: "",
    },
    {
        id: 29,
        ejercicio: "Sentadilla cosaca",
        categoria: "Gluteos",
        img: "https://www.docteur-fitness.com/wp-content/uploads/2022/01/cossack-squat.gif",
        descripcion: "La sentadilla cosaca o side squat (en inglés Cossack Squat o Side Squat ) es una variación de la sentadilla para los aductores, que consiste en doblar una pierna hacia un lado y luego la otra. Las sentadillas, las estocadas y la mayoría de los demás ejercicios para las piernas trabajan las piernas hacia arriba y hacia abajo y/o hacia adelante y hacia atrás. Estos tipos de movimientos tienen lugar en el plano sagital de movimiento.  Las sentadillas cosacas trabajan las piernas lateralmente, en un plano frontal, lo cual es mucho menos común. Las sentadillas cosacas trabajan los cuádriceps , los isquiotibiales , los glúteos , las pantorrillas , el núcleo , los músculos posturales de la espalda , los aductores y los flexores de la cadera.  Este ejercicio también ayuda a mejorar la salud de sus articulaciones, identificar y prevenir desequilibrios y mejorar el rendimiento en múltiples áreas.",
        consejo1: "El principal error de las sentadillas cosacas es hacer el movimiento demasiado rápido, sin ningún control. Lentitud y regularidad son las palabras clave aquí. Mantenga un ritmo controlado, manteniendo una tensión constante en los músculos en todo el rango de movimiento.",
        consejo2: "Trate de mantenerse lo más recto posible. La respiración controlada y el compromiso central son esenciales. También mantén firmes tus oblicuos, para evitar girar hacia un lado durante el movimiento.",
        consejo3: "Este ejercicio requiere una buena flexibilidad. Estirar los aductores y los isquiotibiales, además de trabajar la movilidad del tobillo en paralelo a estos movimientos, te permitirá realizar una correcta sentadilla cosaca.",
        consejo4: "Si no tiene suficiente rango de movimiento en el tobillo, tendrá la tentación de levantar el talón del piso para agacharse más. Solo desciende lo más lejos que puedas sin que se levante el talón. Trabaje en ejercicios de movilidad del tobillo mientras espera.",
        consejo5: "",
        paso1: "Adopta una postura amplia para que tus piernas formen un triángulo equilátero con el suelo. Manténgalos rectos. Asegúrate de que los dedos de tus pies apunten hacia adelante.",
        paso2: "Inhala, contrae la correa abdominal y los glúteos.",
        paso3: "Cambie su peso a la pierna derecha, doble la rodilla derecha y siéntese lo más atrás posible durante el descenso.",
        paso4: "Su pierna izquierda debe permanecer recta (extendida) mientras su pie izquierdo se balancea en el talón. Mantenga los dedos de los pies apuntando hacia arriba.",
        paso5: "Mantenga su talón derecho en el piso y mantenga su torso recto.",
        paso6: "Haga una pausa en la parte inferior del descenso, exhale y vuelva a subir a la posición inicial. Repite el ejercicio con la pierna contraria.",
        paso7: "",
        paso8: "",
        paso9: "",
        paso10: "",
    },

    {
        id: 30,
        ejercicio: "",
        categoria: "Gluteos",
        img: "",
        descripcion: "",
        consejo1: "",
        consejo2: "",
        consejo3: "",
        consejo4: "",
        consejo5: "",
        paso1: "",
        paso2: "",
        paso3: "",
        paso4: "",
        paso5: "",
        paso6: "",
        paso7: "",
        paso8: "",
        paso9: "",
        paso10: "",
    },




];

export default ejercicios;